name: Deploy Zabbix Monitoring Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Vérification de Docker
        run: docker --version

      - name: Lancement du stack Zabbix
        run: docker compose up -d

      - name: Vérification des conteneurs
        run: docker compose ps